### ISSUE TITLE
有遇到经常掉线么。

### ISSUE THREAD

**Issue by clippers1** [endokai/docker-wechatPc#13]
docker 日志{"loginStatus":0}

**Comment by tom-snow** [comment]
我挂了 36 小时了，一切正常。
你是不是有在其他地方登陆微信 pc 客户端顶掉了或者手机的客户端“切换账号”/“退出登陆”？
另外提交 issue 能不能给出更多有用的信息？

**Comment by clippers1** [comment]
> 我挂了 36 小时了，一切正常。 你是不是有在其他地方登陆微信 pc 客户端顶掉了或者手机的客户端“切换账号”/“退出登陆”？ 另外提交 issue 能不能给出更多有用的信息？

ok。不好意思，今天吧docker日志清空了 我确实也看不到任何报错信息，用的tx云2c4g的服务器，基本几个小时，手机显示还是登录，但是ws.onmessage 却拿不到回调内容了。
