### ISSUE TITLE
运行服务卡死

### ISSUE THREAD

**Issue by gclm** [endokai/docker-wechatPc#3]
## docker 容器
![image](https://user-images.githubusercontent.com/27618687/152906560-3c0eeafb-6332-4d0b-865c-37a8529ffe9a.png)

## vnc 服务
![image](https://user-images.githubusercontent.com/27618687/152906507-73b3d2c0-b0aa-4827-ab6e-a5ef324b9056.png)
![image](https://user-images.githubusercontent.com/27618687/152908379-9792fbd2-4928-424e-a196-e0b792fe1359.png)

**Comment by tom-snow** [comment]
> ## docker 容器
> ![image](https://user-images.githubusercontent.com/27618687/152906560-3c0eeafb-6332-4d0b-865c-37a8529ffe9a.png)
> 
> ## vnc 服务
> ![image](https://user-images.githubusercontent.com/27618687/152906507-73b3d2c0-b0aa-4827-ab6e-a5ef324b9056.png) ![image](https://user-images.githubusercontent.com/27618687/152908379-9792fbd2-4928-424e-a196-e0b792fe1359.png)

建议贴一下 docker logs
